create table authors(
 athr_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 10)
    unique,
 author_name varchar2(100) primary key
);
create table books(
 book_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 10)
    unique,
 book_name varchar2(100) primary key,
 athr_id int,
 constraint fk_book_athr foreign key (athr_id) references authors(athr_id)
);
create table readers(
 read_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 10)
    unique,
 reader_name varchar2(100) primary key,
 birthday date
);
create table facts(
 fact_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 10)
    primary key,
 book_id int,
 read_id int,
 constraint fk_rqst_book foreign key (book_id) references books(book_id),
 constraint fk_rqst_read foreign key (read_id) references readers(read_id)
);

create table tmp_load_table(
 author varchar2(100),
 book varchar2(100),
 reader varchar2(100),
 reader_birthday date
);
